# Configuration for request-info
# https://github.com/behaviorbot/request-info

# *Required* Comment to reply with
requestInfoReplyComment: >
  We would appreciate it if you could provide us with more info about this issue or pull request so we can better understand your code changes! ðŸš€

# *OPTIONAL* default titles to check against for lack of descriptiveness
# MUST BE ALL LOWERCASE
requestInfoDefaultTitles:
  - update readme.md
  - updates
  - fixes
  - new feature

# *OPTIONAL* Label to be added to Issues and Pull Requests with insufficient information given
requestInfoLabelToAdd: needs-more-info

####################################################################################################
# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome
# Comment to be posted to on first time issues

newIssueWelcomeComment: >
  Hey! Thanks for the issue!
  Please make sure you have given us enough context and we will review it as soon as possible. â²ï¸
  If you don't hear back from anyone within the next week, feel free to reach out to one of the maintainers.
  And if you haven't already, feel free to contribute a technical interview topic to our repo! Check out the [Contributing Guide!](https://github.com/YearOne-Prep/YearOne-prep-challenges/blob/main/.github/CONTRIBUTING.md)

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome
# Comment to be posted to on PRs from first time contributors in your repository

newPRWelcomeComment: >
  Thanks for your contribution!
  Please make sure you have followed our contributing guidelines and we will review it as soon as possible. â²ï¸
  If you don't hear back from anyone within the next week, feel free to reach out to one of the maintainers. ðŸ’›

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge
# Comment to be posted to on pull requests merged by a first time user

firstPRMergeComment: >
  Congrats on merging your first pull request!ðŸŽ‰


  ![Applause](https://tenor.com/view/clapping-leonardo-dicaprio-leo-dicaprio-gif-10584134.gif)
